package de.artemis.matterworks.common.datagen;

import de.artemis.matterworks.Matterworks;
import de.artemis.matterworks.common.registry.ModBlocks;
import de.artemis.matterworks.common.registry.ModItems;
import net.minecraft.data.PackOutput;

public class ModLanguageProvider extends net.neoforged.neoforge.common.data.LanguageProvider {
    public ModLanguageProvider(PackOutput output, String locale) {
        super(output, Matterworks.MOD_ID, locale);
    }

    @Override
    protected void addTranslations() {
        add("itemGroup.matterworks", "Matterworks");
        add("tooltip.matterworks.stored_matter", "Stored Matter: %s");
        add("tooltip.matterworks.energy", "Energy: %s / %s FE");
        add("tooltip.matterworks.fluid", "Fluid: %s / %s mB");
        add("tooltip.matterworks.progress", "Progress: %s / %s");
        add("tooltip.matterworks.raw_matter_tank", "Raw Matter: %s / %s mB");
        add("tooltip.matterworks.refined_matter_tank", "Refined Matter: %s / %s mB");
        add("tooltip.matterworks.matter_sludge_tank", "Matter Sludge: %s / %s mB");
        add("tooltip.matterworks.unstable_matter_tank", "Unstable Matter: %s / %s mB");
        add("effect.matterworks.molecular_displacement", "Molecular Displacement");
        add("item.minecraft.potion.effect.molecular_displacement", "Potion of Molecular Displacement");
        add("item.minecraft.splash_potion.effect.molecular_displacement", "Splash Potion of Molecular Displacement");
        add("item.minecraft.lingering_potion.effect.molecular_displacement", "Lingering Potion of Molecular Displacement");
        add("item.minecraft.tipped_arrow.effect.molecular_displacement", "Arrow of Molecular Displacement");
        add("tooltip.matterworks.constructor_matter", "Matter Dust: %s / %s");
        add("tooltip.matterworks.matter_power_bank", "Automatically charges FE items in inventory, hotbar, and armor.");
        add("tooltip.matterworks.matter_power_bank.auto_charge_enabled", "Auto-Charge: Enabled");
        add("tooltip.matterworks.matter_power_bank.auto_charge_disabled", "Auto-Charge: Disabled");
        add("tooltip.matterworks.matter_power_bank.toggle", "Right-click to toggle auto-charge.");
        add("enchantment.matterworks.crystal_tuning", "Crystal Tuning");
        add("tooltip.matterworks.crystal_tuning_book", "Improves the charge of crystals mined from Power Crystal Ore.");
        add("tooltip.matterworks.encoded_with", "Encoded With: %s");
        add("tooltip.matterworks.pattern_progress", "Pattern Progress: %s / %s");
        add("tooltip.matterworks.power_crystal_charge", "Charge: %s / %s");
        add("tooltip.matterworks.unstable_matter_bucket.rupture", "Containment Failure In: %ss");
        add("tooltip.matterworks.crimson_power_crystal", "Speeds machine processing but increases FE use while charged.");
        add("tooltip.matterworks.azure_power_crystal", "Expands machine fluid tank storage while charged.");
        add("tooltip.matterworks.verdant_power_crystal", "Reduces FE use and expands internal FE storage while charged.");

        add("fluid_type.matterworks.raw_matter", "Raw Matter");
        add("fluid_type.matterworks.refined_matter", "Refined Matter");
        add("fluid_type.matterworks.matter_sludge", "Matter Sludge");
        add("fluid_type.matterworks.unstable_matter", "Unstable Matter");
        addItem(ModItems.RAW_MATTER_BUCKET, "Raw Matter Bucket");
        addItem(ModItems.REFINED_MATTER_BUCKET, "Refined Matter Bucket");
        addItem(ModItems.MATTER_SLUDGE_BUCKET, "Matter Sludge Bucket");
        addItem(ModItems.UNSTABLE_MATTER_BUCKET, "Unstable Matter Bucket");
        addItem(ModItems.MATTER_DUST, "Matter Dust");
        addItem(ModItems.MATTER_SINGULARITY, "Matter Singularity");
        addItem(ModItems.ENTROPIC_MATTER, "Entropic Matter");
        addItem(ModItems.STABILIZED_MATTER_PLATE, "Stabilized Matter Plate");
        addItem(ModItems.CONDUCTIVE_MATTER_COIL, "Conductive Matter Coil");
        addItem(ModItems.VERDANT_CRYSTAL_LATTICE, "Verdant Crystal Lattice");
        addItem(ModItems.CRIMSON_FLUX_COIL, "Crimson Flux Coil");
        addItem(ModItems.MULTIBLOCK_GLASS_PANE, "Multiblock Glass Pane");
        addItem(ModItems.BATTERY_CORE_ASSEMBLY, "Battery Core Assembly");
        addItem(ModItems.EMPTY_TEMPLATE, "Empty Template");
        addItem(ModItems.MATTER_ARCHITECT, "Matter Architect");
        addItem(ModItems.MATTER_ITEM_FILTER, "Item Filter Card");
        addItem(ModItems.MATTER_FLUID_FILTER, "Fluid Filter Card");
        addItem(ModItems.ENCODED_TEMPLATE, "Encoded Template");
        addItem(ModItems.NETWORK_DATA_CARD, "Network Data Card");
        addItem(ModItems.NETWORK_REMOTE_TERMINAL, "Network Remote Terminal");
        addItem(ModItems.CRIMSON_POWER_CRYSTAL, "Crimson Power Crystal");
        addItem(ModItems.AZURE_POWER_CRYSTAL, "Azure Power Crystal");
        addItem(ModItems.VERDANT_POWER_CRYSTAL, "Verdant Power Crystal");
        addItem(ModItems.MATTER_POWER_BANK, "Matter Power Bank");
        add("item.matterworks.encoded_template.filled", "Encoded Template (%s)");
        add("message.matterworks.matter_power_bank.auto_charge_enabled", "Matter Power Bank auto-charge enabled.");
        add("message.matterworks.matter_power_bank.auto_charge_disabled", "Matter Power Bank auto-charge disabled.");
        add("message.matterworks.network_data_card.copied", "Copied settings from %s.");
        add("message.matterworks.network_data_card.applied", "Applied settings to %s.");
        add("message.matterworks.network_data_card.mismatch", "Stored settings are for %s. Sneak-right-click to overwrite.");
        add("message.matterworks.network_remote_terminal.linked", "Linked terminal to %s: %s.");
        add("message.matterworks.network_remote_terminal.cleared", "Cleared linked network terminal target.");
        add("message.matterworks.network_remote_terminal.unlinked", "This terminal is not linked to a network block.");
        add("message.matterworks.network_remote_terminal.wrong_dimension", "%s is in a different dimension.");
        add("message.matterworks.network_remote_terminal.missing_target", "Linked target %s is missing or no longer valid.");
        add("tooltip.matterworks.network_data_card.empty", "Right-click a compatible block to copy its settings.");
        add("tooltip.matterworks.network_data_card.stored", "Stored Settings: %s");
        add("tooltip.matterworks.network_data_card.apply_hint", "Right-click the same block type to apply.");
        add("tooltip.matterworks.network_data_card.overwrite_hint", "Sneak-right-click to overwrite the stored settings.");
        add("tooltip.matterworks.network_data_card.unknown", "Unknown Block");
        add("tooltip.matterworks.network_remote_terminal.empty", "Right-click a network controller or monitor to link it.");
        add("tooltip.matterworks.network_remote_terminal.linked", "Linked %s: %s");
        add("tooltip.matterworks.network_remote_terminal.open_hint", "Right-click to open the linked terminal remotely.");
        add("tooltip.matterworks.network_remote_terminal.clear_hint", "Sneak-right-click in air to clear the link.");
        add("tooltip.matterworks.network_remote_terminal.unknown", "Unknown Target");
        add("item.matterworks.network_remote_terminal.target.controller", "Controller");
        add("item.matterworks.network_remote_terminal.target.monitor", "Monitor");

        addBlock(ModBlocks.MATTER_RECYCLER, "Matter Recycler");
        addBlock(ModBlocks.MATTER_STABILIZER, "Matter Stabilizer");
        addBlock(ModBlocks.MATTER_ANALYZER, "Matter Analyzer");
        addBlock(ModBlocks.MATTER_CONSTRUCTOR, "Matter Constructor");
        addBlock(ModBlocks.COMBUSTION_GENERATOR, "Combustion Generator");
        addBlock(ModBlocks.MATTER_ENERGY_CELL, "Energy Cell");
        addBlock(ModBlocks.MATTER_BATTERY_CORE, "Matter Battery Core");
        addBlock(ModBlocks.MULTIBLOCK_FRAME, "Multiblock Frame");
        addBlock(ModBlocks.MULTIBLOCK_CASING, "Multiblock Casing");
        addBlock(ModBlocks.MULTIBLOCK_PORT, "Multiblock Port");
        addBlock(ModBlocks.MULTIBLOCK_GLASS, "Multiblock Glass");
        addBlock(ModBlocks.MATTER_CAPACITOR_CELL, "Matter Capacitor Cell");
        addBlock(ModBlocks.MATTER_INDUCTION_RELAY, "Matter Induction Relay");
        addBlock(ModBlocks.FLUID_TANK, "Fluid Tank");
        addBlock(ModBlocks.MATTER_STORAGE_BARREL, "Matter Storage Barrel");
        addBlock(ModBlocks.MATTER_PYLON, "Matter Pylon");
        addBlock(ModBlocks.SINGULARITY_LINK_FRAME, "Singularity Link Frame");
        addBlock(ModBlocks.SINGULARITY_LINK, "Singularity Link");
        addBlock(ModBlocks.MATTER_NETWORK_CONTROLLER, "Matter Network Controller");
        addBlock(ModBlocks.MATTER_NETWORK_MONITOR, "Matter Network Monitor");
        addBlock(ModBlocks.CREATIVE_SOURCE, "Creative Source");
        addBlock(ModBlocks.CREATIVE_SINK, "Creative Sink");
        addBlock(ModBlocks.MATTER_SEPARATOR, "Matter Separator");
        addBlock(ModBlocks.GRAVITIC_CONDENSER, "Gravitic Condenser");
        addBlock(ModBlocks.POWER_CRYSTAL_CHARGER, "Charger");
        addBlock(ModBlocks.POWER_CRYSTAL_ORE, "Power Crystal Ore");
        add("message.matterworks.pylon.mode.disabled", "Disabled");
        add("message.matterworks.pylon.mode.export", "Export");
        add("message.matterworks.pylon.mode.import", "Import");
        add("message.matterworks.pylon.mode.import_export", "Import/Export");
        add("message.matterworks.pylon.mode_changed", "Pylon mode: %s");
        add("message.matterworks.pylon.link_started", "Link start saved at %s");
        add("message.matterworks.pylon.link_cancelled", "Matter network link cancelled.");
        add("message.matterworks.pylon.link_created", "Matter network nodes linked.");
        add("message.matterworks.pylon.link_removed", "Matter network link removed.");
        add("message.matterworks.pylon.link_too_far", "Matter network nodes are too far apart. Max span: %s blocks.");
        add("message.matterworks.pylon.link_limit", "This matter network node is already using all %s links.");
        add("message.matterworks.pylon.link_incompatible", "These matter network nodes cannot link directly.");
        add("message.matterworks.pylon.invalid_target", "Link target must be another matter network node in the same dimension.");
        add("message.matterworks.creative_source.status", "Source FE: %s / %s | Items: %s | Fluid: %s / %s mB");
        add("message.matterworks.creative_sink.status", "Sink FE: %s / %s | Items: %s | Fluid: %s / %s mB");
        add("message.matterworks.matter_battery.assembled", "Matter Battery assembled.");
        add("message.matterworks.matter_battery.disassembled", "Matter Battery disassembled.");
        add("message.matterworks.matter_battery.invalid", "Matter Battery invalid: %s");
        add("message.matterworks.matter_battery.port_mode", "Battery Port mode: %s");
        add("key.categories.matterworks", "Matterworks");
        add("key.matterworks.architect.layer_up", "Matter Architect Layer Up");
        add("key.matterworks.architect.layer_down", "Matter Architect Layer Down");
        add("screen.matterworks.matter_pylon.id", "ID");
        add("screen.matterworks.matter_pylon.mode", "Mode");
        add("screen.matterworks.matter_pylon.channel", "Channel");
        add("screen.matterworks.matter_pylon.channel.energy", "Energy");
        add("screen.matterworks.matter_pylon.channel.items", "Items");
        add("screen.matterworks.matter_pylon.channel.fluids", "Fluids");
        add("screen.matterworks.matter_pylon.channel.redstone", "Redstone");
        add("screen.matterworks.matter_pylon.channel.energy.short", "FE");
        add("screen.matterworks.matter_pylon.channel.items.short", "IT");
        add("screen.matterworks.matter_pylon.channel.fluids.short", "FL");
        add("screen.matterworks.matter_pylon.channel.redstone.short", "RS");
        add("screen.matterworks.matter_pylon.link_hint", "Shift-right-click pylons to link them.");
        add("screen.matterworks.matter_network.title", "Matter Network");
        add("screen.matterworks.matter_network.id", "ID");
        add("screen.matterworks.matter_network.mode", "Mode");
        add("screen.matterworks.matter_network.channel", "Channel");
        add("screen.matterworks.matter_network.item_filter", "Item Filter Card");
        add("screen.matterworks.matter_network.fluid_filter", "Fluid Filter Card");
        add("screen.matterworks.matter_network.whitelist_short", "W");
        add("screen.matterworks.matter_network.blacklist_short", "B");
        add("screen.matterworks.matter_network.import_short", "IN");
        add("screen.matterworks.matter_network.export_short", "OUT");
        add("screen.matterworks.matter_network.link_hint", "Shift-right-click nodes to link them.");
        add("screen.matterworks.matter_network.open", "Network");
        add("screen.matterworks.matter_network.energy_cell", "Energy Cell Network");
        add("screen.matterworks.matter_network.fluid_tank", "Fluid Tank Network");
        add("screen.matterworks.matter_network.storage_barrel", "Matter Storage Barrel Network");
        add("screen.matterworks.matter_network_controller.connected_nodes", "Connected Nodes: %s");
        add("screen.matterworks.matter_network_controller.details", "Details");
        add("screen.matterworks.matter_network_controller.no_selection", "Select a connected node.");
        add("screen.matterworks.matter_network_controller.position", "Pos: %s, %s, %s");
        add("screen.matterworks.matter_network_controller.status.active", "Status: Active");
        add("screen.matterworks.matter_network_controller.status.idle", "Status: Idle");
        add("screen.matterworks.matter_network_controller.links", "Links: %s");
        add("screen.matterworks.matter_network_controller.open_gui", "Open GUI");
        add("screen.matterworks.matter_network_controller.locate", "Locate");
        add("screen.matterworks.matter_network_controller.inactive", "Inactive");
        add("screen.matterworks.singularity_link.formed", "Structure: Formed");
        add("screen.matterworks.singularity_link.incomplete", "Structure: Incomplete");
        add("screen.matterworks.singularity_link.linked", "Partner: Linked");
        add("screen.matterworks.singularity_link.waiting", "Partner: Waiting");
        add("screen.matterworks.matter_filter.entries", "Filter Entries");
        add("screen.matterworks.matter_filter.clear", "Clear");
        add("screen.matterworks.matter_filter.sort", "Sort");
        add("screen.matterworks.matter_filter.clean", "Clean");
        add("screen.matterworks.matter_battery.structure", "Structure");
        add("screen.matterworks.matter_battery.formed", "Formed");
        add("screen.matterworks.matter_battery.not_formed", "Not Formed");
        add("screen.matterworks.matter_battery.cells", "Cells: %s");
        add("screen.matterworks.matter_battery.relays", "Relays: %s");
        add("screen.matterworks.matter_battery.ports", "Ports: %s");
        add("screen.matterworks.matter_battery.energy", "Energy");
        add("screen.matterworks.matter_battery.stored", "Stored: %s FE");
        add("screen.matterworks.matter_battery.capacity", "Capacity: %s FE");
        add("screen.matterworks.matter_battery.transfer", "Transfer: %s FE/t");
        add("screen.matterworks.matter_battery.layer", "Layer: %s / %s");
        add("screen.matterworks.matter_battery.tab_stats", "Stats");
        add("screen.matterworks.matter_battery.tab_ports", "Ports");
        add("screen.matterworks.matter_battery.graph_charge", "Charge History");
        add("screen.matterworks.matter_battery.graph_rates", "Rate History");
        add("screen.matterworks.matter_battery.input_rate", "Input: %s FE/t");
        add("screen.matterworks.matter_battery.output_rate", "Output: %s FE/t");
        add("screen.matterworks.matter_battery.port_tab", "Port List");
        add("screen.matterworks.matter_battery.port_details", "Port Details");
        add("screen.matterworks.matter_battery.port_none", "Select a port.");
        add("screen.matterworks.matter_battery.port_limit", "Max Speed: %s FE/t");
        add("screen.matterworks.matter_battery.preview_title", "Preview");
        add("screen.matterworks.matter_battery.preview_hint", "Controller handles hologram build");
        add("screen.matterworks.matter_battery.port_hint", "Ports replace frame or casing");
        add("screen.matterworks.matter_battery.glass_hint", "Glass replaces casing");
        add("screen.matterworks.matter_battery.status_hint", "Open from any formed battery block");
        add("screen.matterworks.matter_battery.shell_hint", "Ports and glass stay on the shell");
        add("screen.matterworks.matter_battery.preview_on", "Preview: On");
        add("screen.matterworks.matter_battery.preview_off", "Preview");
    }
}

