package de.artemis.matterworks.common.datagen;

import de.artemis.matterworks.Matterworks;
import de.artemis.matterworks.common.registry.ModBlocks;
import de.artemis.matterworks.common.registry.ModItems;
import net.minecraft.data.PackOutput;

public class ModLanguageProvider extends net.neoforged.neoforge.common.data.LanguageProvider {
    public ModLanguageProvider(PackOutput output, String locale) {
        super(output, Matterworks.MOD_ID, locale);
    }

    @Override
    protected void addTranslations() {
        add("itemGroup.matterworks", "Matterworks");
        add("tooltip.matterworks.stored_matter", "Stored Matter: %s");
        add("tooltip.matterworks.energy", "Energy: %s / %s FE");
        add("tooltip.matterworks.fluid", "Fluid: %s / %s mB");
        add("tooltip.matterworks.progress", "Progress: %s / %s");
        add("tooltip.matterworks.raw_matter_tank", "Raw Matter: %s / %s mB");
        add("tooltip.matterworks.refined_matter_tank", "Refined Matter: %s / %s mB");
        add("tooltip.matterworks.matter_sludge_tank", "Matter Sludge: %s / %s mB");
        add("tooltip.matterworks.unstable_matter_tank", "Unstable Matter: %s / %s mB");
        add("effect.matterworks.molecular_displacement", "Molecular Displacement");
        add("item.minecraft.potion.effect.molecular_displacement", "Potion of Molecular Displacement");
        add("item.minecraft.splash_potion.effect.molecular_displacement", "Splash Potion of Molecular Displacement");
        add("item.minecraft.lingering_potion.effect.molecular_displacement", "Lingering Potion of Molecular Displacement");
        add("item.minecraft.tipped_arrow.effect.molecular_displacement", "Arrow of Molecular Displacement");
        add("tooltip.matterworks.constructor_matter", "Matter Dust: %s / %s");
        add("tooltip.matterworks.matter_power_bank", "Automatically charges FE items in inventory, hotbar, and armor.");
        add("tooltip.matterworks.matter_power_bank.auto_charge_enabled", "Auto-Charge: Enabled");
        add("tooltip.matterworks.matter_power_bank.auto_charge_disabled", "Auto-Charge: Disabled");
        add("tooltip.matterworks.matter_power_bank.toggle", "Right-click to toggle auto-charge.");
        add("enchantment.matterworks.crystal_tuning", "Crystal Tuning");
        add("tooltip.matterworks.crystal_tuning_book", "Improves the charge of crystals mined from Power Crystal Ore.");
        add("tooltip.matterworks.encoded_with", "Encoded With: %s");
        add("tooltip.matterworks.pattern_progress", "Pattern Progress: %s / %s");
        add("tooltip.matterworks.power_crystal_charge", "Charge: %s / %s");
        add("tooltip.matterworks.unstable_matter_bucket.rupture", "Containment Failure In: %ss");
        add("tooltip.matterworks.crimson_power_crystal", "Speeds machine processing but increases FE use while charged.");
        add("tooltip.matterworks.azure_power_crystal", "Expands machine fluid tank storage while charged.");
        add("tooltip.matterworks.verdant_power_crystal", "Reduces FE use and expands internal FE storage while charged.");

        add("fluid_type.matterworks.raw_matter", "Raw Matter");
        add("fluid_type.matterworks.refined_matter", "Refined Matter");
        add("fluid_type.matterworks.matter_sludge", "Matter Sludge");
        add("fluid_type.matterworks.unstable_matter", "Unstable Matter");
        addItem(ModItems.RAW_MATTER_BUCKET, "Raw Matter Bucket");
        addItem(ModItems.REFINED_MATTER_BUCKET, "Refined Matter Bucket");
        addItem(ModItems.MATTER_SLUDGE_BUCKET, "Matter Sludge Bucket");
        addItem(ModItems.UNSTABLE_MATTER_BUCKET, "Unstable Matter Bucket");
        addItem(ModItems.MATTER_DUST, "Matter Dust");
        addItem(ModItems.ENTROPIC_MATTER, "Entropic Matter");
        addItem(ModItems.EMPTY_TEMPLATE, "Empty Template");
        addItem(ModItems.MATTER_ITEM_FILTER, "Item Filter");
        addItem(ModItems.MATTER_FLUID_FILTER, "Fluid Filter");
        addItem(ModItems.ENCODED_TEMPLATE, "Encoded Template");
        addItem(ModItems.CRIMSON_POWER_CRYSTAL, "Crimson Power Crystal");
        addItem(ModItems.AZURE_POWER_CRYSTAL, "Azure Power Crystal");
        addItem(ModItems.VERDANT_POWER_CRYSTAL, "Verdant Power Crystal");
        addItem(ModItems.MATTER_POWER_BANK, "Matter Power Bank");
        add("item.matterworks.encoded_template.filled", "Encoded Template (%s)");
        add("message.matterworks.matter_power_bank.auto_charge_enabled", "Matter Power Bank auto-charge enabled.");
        add("message.matterworks.matter_power_bank.auto_charge_disabled", "Matter Power Bank auto-charge disabled.");

        addBlock(ModBlocks.MATTER_RECYCLER, "Matter Recycler");
        addBlock(ModBlocks.MATTER_STABILIZER, "Matter Stabilizer");
        addBlock(ModBlocks.MATTER_ANALYZER, "Matter Analyzer");
        addBlock(ModBlocks.MATTER_CONSTRUCTOR, "Matter Constructor");
        addBlock(ModBlocks.MATTER_GENERATOR, "Matter Generator");
        addBlock(ModBlocks.MATTER_ENERGY_CELL, "Matter Energy Cell");
        addBlock(ModBlocks.MATTER_FLUID_TANK, "Matter Fluid Tank");
        addBlock(ModBlocks.MATTER_STORAGE_BARREL, "Matter Storage Barrel");
        addBlock(ModBlocks.MATTER_PYLON, "Matter Pylon");
        addBlock(ModBlocks.MATTER_NETWORK_CONTROLLER, "Matter Network Controller");
        addBlock(ModBlocks.CREATIVE_SOURCE, "Creative Source");
        addBlock(ModBlocks.CREATIVE_SINK, "Creative Sink");
        addBlock(ModBlocks.MATTER_SEPARATOR, "Matter Separator");
        addBlock(ModBlocks.HARDENED_SLUDGE, "Hardened Sludge");
        addBlock(ModBlocks.POWER_CRYSTAL_CHARGER, "Power Crystal Charger");
        addBlock(ModBlocks.POWER_CRYSTAL_ORE, "Power Crystal Ore");
        add("message.matterworks.pylon.mode.disabled", "Disabled");
        add("message.matterworks.pylon.mode.export", "Export");
        add("message.matterworks.pylon.mode.import", "Import");
        add("message.matterworks.pylon.mode.import_export", "Import/Export");
        add("message.matterworks.pylon.mode_changed", "Pylon mode: %s");
        add("message.matterworks.pylon.link_started", "Link start saved at %s");
        add("message.matterworks.pylon.link_cancelled", "Matter network link cancelled.");
        add("message.matterworks.pylon.link_created", "Matter network nodes linked.");
        add("message.matterworks.pylon.link_removed", "Matter network link removed.");
        add("message.matterworks.pylon.link_too_far", "Matter network nodes are too far apart. Max span: %s blocks.");
        add("message.matterworks.pylon.link_limit", "This matter network node is already using all %s links.");
        add("message.matterworks.pylon.link_incompatible", "These matter network nodes cannot link directly.");
        add("message.matterworks.pylon.invalid_target", "Link target must be another matter network node in the same dimension.");
        add("message.matterworks.creative_source.status", "Source FE: %s / %s | Items: %s | Fluid: %s / %s mB");
        add("message.matterworks.creative_sink.status", "Sink FE: %s / %s | Items: %s | Fluid: %s / %s mB");
        add("screen.matterworks.matter_pylon.id", "ID");
        add("screen.matterworks.matter_pylon.mode", "Mode");
        add("screen.matterworks.matter_pylon.channel", "Channel");
        add("screen.matterworks.matter_pylon.channel.energy", "Energy");
        add("screen.matterworks.matter_pylon.channel.items", "Items");
        add("screen.matterworks.matter_pylon.channel.fluids", "Fluids");
        add("screen.matterworks.matter_pylon.channel.redstone", "Redstone");
        add("screen.matterworks.matter_pylon.channel.energy.short", "FE");
        add("screen.matterworks.matter_pylon.channel.items.short", "IT");
        add("screen.matterworks.matter_pylon.channel.fluids.short", "FL");
        add("screen.matterworks.matter_pylon.channel.redstone.short", "RS");
        add("screen.matterworks.matter_pylon.link_hint", "Shift-right-click pylons to link them.");
        add("screen.matterworks.matter_network.title", "Matter Network");
        add("screen.matterworks.matter_network.id", "ID");
        add("screen.matterworks.matter_network.mode", "Mode");
        add("screen.matterworks.matter_network.channel", "Channel");
        add("screen.matterworks.matter_network.item_filter", "Item Filter");
        add("screen.matterworks.matter_network.fluid_filter", "Fluid Filter");
        add("screen.matterworks.matter_network.whitelist_short", "W");
        add("screen.matterworks.matter_network.blacklist_short", "B");
        add("screen.matterworks.matter_network.import_short", "IN");
        add("screen.matterworks.matter_network.export_short", "OUT");
        add("screen.matterworks.matter_network.link_hint", "Shift-right-click nodes to link them.");
        add("screen.matterworks.matter_network.open", "Network");
        add("screen.matterworks.matter_network.energy_cell", "Matter Energy Cell Network");
        add("screen.matterworks.matter_network.fluid_tank", "Matter Fluid Tank Network");
        add("screen.matterworks.matter_network.storage_barrel", "Matter Storage Barrel Network");
        add("screen.matterworks.matter_network_controller.connected_nodes", "Connected Nodes: %s");
        add("screen.matterworks.matter_network_controller.details", "Details");
        add("screen.matterworks.matter_network_controller.no_selection", "Select a connected node.");
        add("screen.matterworks.matter_network_controller.position", "Pos: %s, %s, %s");
        add("screen.matterworks.matter_network_controller.status.active", "Status: Active");
        add("screen.matterworks.matter_network_controller.status.idle", "Status: Idle");
        add("screen.matterworks.matter_network_controller.links", "Links: %s");
        add("screen.matterworks.matter_network_controller.open_gui", "Open GUI");
        add("screen.matterworks.matter_network_controller.locate", "Locate");
        add("screen.matterworks.matter_network_controller.inactive", "Inactive");
        add("screen.matterworks.matter_filter.entries", "Filter Entries");
        add("screen.matterworks.matter_filter.clear", "Clear");
    }
}
